### ISSUE TITLE
使用方法

### ISSUE THREAD

**Issue by Littlemyself** [liuly0322/hexo-theme-myscape#1]
能不能简单的说下主要的页面设置参数了

![17172021202120212033](https://user-images.githubusercontent.com/33508419/134169017-3d3d1b72-5789-456f-bc61-5901466d1f3f.png)

没有参数报错了

**Comment by liuly0322** [comment]
`npm i --save hexo-wordcount`
写文档的时候插件啥的没写清楚，稍后会补上

**Comment by liuly0322** [comment]
已经更新 readme 中主题使用说明
